-record(update_block, {update_type,
                       object_guid,
                       object_type,
                       update_flags,
                       movement_flags,
                       unknown = 0,
                       game_time,
                       position,
                       fall_time,
                       speeds,
                       mask,
                       fields}).